{
  "openapi": "3.0.3",
  "info": {
    "title": "Tasmota Device Manager API",
    "description": "Device manager for Tasmota devices via MQTT [Source](https://github.com/mbezuidenhout/tasmota.mqtt.device.manager).",
    "version": "0.1.0",
    "contact": {
      "email": "marius.bezuidenhout@gmail.com"
    }
  },
  "servers": [
    {
      "url": "https://localhost:43443/v3",
      "description": "Optional server description, e.g. Main (production) server"
    },
    {
      "url": "http://staging-api.example.com",
      "description": "Optional server description, e.g. Internal staging server for testing"
    }
  ],
  "tags": [
    {
      "name": "Session",
      "description": "MQTT and session management"
    },
    {
      "name": "Device",
      "description": "Request and update device details",
      "externalDocs": {
        "description": "Find out more",
        "url": "https://tasmota.github.io"
      }
    },
    {
      "name": "Sensor",
      "description": "Request details about sensors"
    }
  ],
  "paths": {
    "/mqtt/connect": {
      "post": {
        "security": [],
        "tags": [
          "Session"
        ],
        "summary": "Sets the MQTT host options",
        "responses": {
          "200": {
            "description": "Successful connection",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Session"
                }
              }
            }
          },
          "503": {
            "description": "Connection refused"
          }
        },
        "requestBody": {
          "description": "MQTT host in the format tcp://host:port with username and password",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MQTTOptions"
              }
            },
            "examples": {}
          }
        }
      }
    },
    "/mqtt": {
      "get": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Session"
        ],
        "summary": "Get MQTT session status",
        "responses": {
          "200": {
            "description": "MQTT session is connected"
          },
          "401": {
            "description": "Session is not connected"
          }
        }
      }
    },
    "/mqtt/disconnect": {
      "get": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Session"
        ],
        "summary": "Disconnect from MQTT server",
        "responses": {
          "204": {
            "description": "Disconnected"
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          }
        }
      }
    },
    "/devices": {
      "post": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Device"
        ],
        "summary": "Returns a list of tasmota devices.",
        "responses": {
          "200": {
            "description": "A JSON array of devices",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "$ref": "#/components/schemas/Device"
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          }
        }
      }
    },
    "/device": {
      "put": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Device"
        ],
        "summary": "Change device settings",
        "parameters": [
          {
            "in": "query",
            "name": "body",
            "description": "Device object that needs to be updated",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/DeviceSettings"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully updated"
          }
        }
      }
    },
    "/device/{deviceTopic}": {
      "get": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Device"
        ],
        "summary": "Returns details of tasmota device by topic.",
        "parameters": [
          {
            "in": "path",
            "name": "deviceTopic",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A JSON object of requested device.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Device"
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          },
          "422": {
            "description": "Required parameter missing."
          }
        }
      },
      "post": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Device"
        ],
        "summary": "Send command and payload to device.",
        "parameters": [
          {
            "in": "path",
            "name": "deviceTopic",
            "schema": {
              "type": "string"
            },
            "required": true
          },
          {
            "in": "query",
            "name": "command",
            "schema": {
              "type": "string"
            },
            "required": true
          },
          {
            "in": "query",
            "name": "payload",
            "schema": {
              "type": "string"
            },
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "Sent"
          }
        }
      }
    },
    "/sensorTypes/{deviceTopic}": {
      "get": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Sensor"
        ],
        "summary": "Returns an array of sensor types.",
        "parameters": [
          {
            "in": "path",
            "name": "deviceTopic",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A JSON object of requested device.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          },
          "422": {
            "description": "Required parameter missing."
          }
        }
      }
    },
    "/sensors/{deviceTopic}": {
      "get": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Sensor"
        ],
        "summary": "Returns all sensor data from device.",
        "parameters": [
          {
            "in": "path",
            "name": "deviceTopic",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A JSON object of sensor data.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "object",
                    "additionalProperties": {
                      "anyOf": [
                        {
                          "$ref": "#/components/schemas/Zigbee"
                        },
                        {
                          "$ref": "#/components/schemas/DS18B20"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          },
          "422": {
            "description": "Required parameter missing."
          }
        }
      }
    },
    "/sensorType/{deviceTopic}/{sensorType}": {
      "get": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Sensor"
        ],
        "summary": "Returns all data for specific sensor type.",
        "parameters": [
          {
            "in": "path",
            "name": "deviceTopic",
            "schema": {
              "type": "string"
            },
            "required": true
          },
          {
            "in": "path",
            "name": "sensorType",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A JSON object of requested sensor type.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "object",
                    "oneOf": [
                      {
                        "$ref": "#/components/schemas/Zigbee"
                      },
                      {
                        "$ref": "#/components/schemas/DS18B20"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          },
          "422": {
            "description": "Required parameter missing."
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-KEY"
      }
    },
    "schemas": {
      "MQTTOptions": {
        "type": "object",
        "properties": {
          "Host": {
            "type": "string"
          },
          "Username": {
            "type": "string"
          },
          "Password": {
            "type": "string"
          },
          "CustomTopic": {
            "type": "string"
          }
        },
        "required": [
          "Host",
          "Username",
          "Password"
        ]
      },
      "Session": {
        "properties": {
          "apikey": {
            "type": "string"
          }
        }
      },
      "DeviceSettings": {
        "type": "object",
        "properties": {
          "Topic": {
            "type": "string",
            "description": "Unique device topic"
          },
          "DeviceName": {
            "type": "string",
            "description": "Device friendly name"
          }
        }
      },
      "Device": {
        "type": "object",
        "properties": {
          "Topic": {
            "type": "string",
            "description": "Unique device topic"
          },
          "FullTopic": {
            "type": "string",
            "description": "Full topic format"
          },
          "DeviceName": {
            "type": "string",
            "description": "Device friendly name"
          },
          "Module": {
            "type": "string",
            "description": "Device module type"
          },
          "Online": {
            "type": "boolean",
            "description": "Device status"
          },
          "LoadAvg": {
            "type": "integer",
            "description": "Load Average"
          },
          "Timezone": {
            "type": "string",
            "description": "Timezone offset from GMT",
            "pattern": "(\\+|\\-)\\d{2}:\\d{2}"
          },
          "Wifi": {
            "$ref": "#/components/schemas/Wifi"
          },
          "StatusNET": {
            "$ref": "#/components/schemas/Network"
          },
          "StatusFWR": {
            "$ref": "#/components/schemas/Firmware"
          }
        },
        "required": [
          "Topic",
          "FullTopic",
          "Online"
        ],
        "example": {
          "Topic": "tasmota-4d9f",
          "FullTopic": "%prefix%/%topic%",
          "Name": "Tasmota",
          "Module": "Sonoff ZbBridge",
          "Online": true,
          "LoadAvg": 19,
          "Timezone": "+02:00",
          "StatusNET": {
            "$ref": "#/components/schemas/Network/example"
          },
          "StatusFWR": {
            "$ref": "#/components/schemas/Firmware/example"
          }
        }
      },
      "Firmware": {
        "type": "object",
        "properties": {
          "Version": {
            "type": "string"
          },
          "BuildDateTime": {
            "type": "string",
            "pattern": "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}"
          },
          "Boot": {
            "type": "integer"
          },
          "Hardware": {
            "type": "string"
          }
        },
        "example": {
          "Version": "10.1.0(zbbridge)",
          "BuildDateTime": "2022-02-03T11:33:56",
          "Boot": 7,
          "Hardware": "ESP8266EX"
        }
      },
      "Network": {
        "type": "object",
        "properties": {
          "IPAddress": {
            "type": "string",
            "pattern": "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))"
          },
          "Hostname": {
            "type": "string",
            "pattern": "([a-zA-Z0-9\\-\\.])+"
          },
          "Gateway": {
            "type": "string",
            "pattern": "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))"
          },
          "Subnetmask": {
            "type": "string",
            "pattern": "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))"
          },
          "DNSServer1": {
            "type": "string",
            "pattern": "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))"
          },
          "DNSServer2": {
            "type": "string",
            "pattern": "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))"
          },
          "Mac": {
            "type": "string",
            "pattern": "([0-9A-F]{2}[:-]){5}([0-9A-F]{2})"
          }
        },
        "example": {
          "IPAddress": "10.0.0.2",
          "Hostname": "switch01.lan",
          "Gateway": "10.0.0.1",
          "Subnetmask": "255.255.255.0",
          "DNSServer1": "10.0.0.1",
          "DNSServer2": "8.8.8.8",
          "Mac": "84:CC:A8:9D:CA:AE"
        }
      },
      "Wifi": {
        "type": "object",
        "properties": {
          "SSId": {
            "type": "string"
          },
          "BSSId": {
            "type": "string"
          },
          "Channel": {
            "type": "integer"
          },
          "Mode": {
            "type": "string"
          },
          "Signal": {
            "type": "integer"
          }
        },
        "example": {
          "SSId": "MyWifiAP",
          "BSSid": "00:00:00:00:00:00",
          "Channel": 9,
          "Mode": "11n",
          "Signal": -38
        }
      },
      "Zigbee": {
        "type": "object",
        "properties": {
          "Device": {
            "type": "string"
          },
          "Name": {
            "type": "string"
          },
          "ModelId": {
            "type": "string"
          },
          "Temperature": {
            "type": "number"
          },
          "Humidity": {
            "type": "number"
          },
          "BatteryPercentage": {
            "type": "integer",
            "minimum": 0,
            "maximum": 100
          },
          "LastSeen": {
            "type": "integer",
            "description": "Last seen in seconds since queried"
          },
          "LastSeenEpoch": {
            "type": "integer",
            "description": "Last seen at seconds since unix epoch UTC"
          },
          "Reachable": {
            "type": "boolean"
          }
        }
      },
      "DS18B20": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "string"
          },
          "Temperature": {
            "type": "number"
          }
        }
      }
    },
    "responses": {
      "UnauthorizedError": {
        "description": "API key is missing or invalid",
        "headers": {
          "WWW_Authenticate": {
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}